# Generated by Django 6.0.6 on 2026-07-05 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField(blank=True, default=list)),
                ('top_20_hr', models.JSONField(blank=True, default=list)),
                ('top_20_technical', models.JSONField(blank=True, default=list)),
                ('top_10_resume_based', models.JSONField(blank=True, default=list)),
                ('top_10_project_based', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='analysis.atsanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockInterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='interview.interviewquestionset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MockInterviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('user_answer', models.TextField()),
                ('confidence_score', models.PositiveIntegerField(default=0)),
                ('grammar_score', models.PositiveIntegerField(default=0)),
                ('technical_accuracy_score', models.PositiveIntegerField(default=0)),
                ('communication_score', models.PositiveIntegerField(default=0)),
                ('star_method_used', models.BooleanField(default=False)),
                ('overall_score', models.PositiveIntegerField(default=0)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('improvements', models.JSONField(blank=True, default=list)),
                ('model_answer', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interview.mockinterviewsession')),
            ],
        ),
    ]
