# Generated by Django 6.0.6 on 2026-07-05 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ATSAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats_score_before', models.PositiveIntegerField(default=0)),
                ('ats_score_after', models.PositiveIntegerField(default=0)),
                ('keyword_match_percent', models.PositiveIntegerField(default=0)),
                ('resume_match_percent', models.PositiveIntegerField(default=0)),
                ('skills_match_percent', models.PositiveIntegerField(default=0)),
                ('recruiter_match_percent', models.PositiveIntegerField(default=0)),
                ('formatting_score', models.PositiveIntegerField(default=0)),
                ('grammar_score', models.PositiveIntegerField(default=0)),
                ('readability_score', models.PositiveIntegerField(default=0)),
                ('matched_keywords', models.JSONField(blank=True, default=list)),
                ('missing_keywords', models.JSONField(blank=True, default=list)),
                ('suggested_keywords', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('weak_sections', models.JSONField(blank=True, default=list)),
                ('strong_sections', models.JSONField(blank=True, default=list)),
                ('section_analysis', models.JSONField(blank=True, default=dict)),
                ('ats_formatting_checks', models.JSONField(blank=True, default=dict)),
                ('overall_summary', models.TextField(blank=True)),
                ('rewritten_sections', models.JSONField(blank=True, default=dict)),
                ('change_log', models.JSONField(blank=True, default=list)),
                ('keywords_inserted', models.JSONField(blank=True, default=list)),
                ('output_docx', models.FileField(blank=True, null=True, upload_to='outputs/docx/')),
                ('output_pdf', models.FileField(blank=True, null=True, upload_to='outputs/pdf/')),
                ('output_txt', models.FileField(blank=True, null=True, upload_to='outputs/txt/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='resumes.jobdescription')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ATS Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='optimization_completed', max_length=100)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='analysis.atsanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Resume History',
                'ordering': ['-created_at'],
            },
        ),
    ]
