# Generated by Django 5.1.4 on 2026-07-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atsanalysis',
            name='fidelity_warnings',
            field=models.JSONField(blank=True, default=list, help_text='Facts (numbers, years, proper nouns) found in the original resume that did not survive into the rewritten text - a safety net against the AI silently dropping real accomplishments.'),
        ),
    ]
