# Generated by Django 5.1.4 on 2026-07-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_atsanalysis_fidelity_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='atsanalysis',
            name='user_approved_keywords',
            field=models.JSONField(blank=True, default=list, help_text='Missing keywords/skills the candidate explicitly confirmed they have, before the rewrite step was allowed to add them.'),
        ),
    ]
